name: "Build GitHub Pages"

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: myme
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Nix Build
      run: |
        nix build
